# specify which database and adapter to use for which environment
# default: &default
#   adapter: postgresql
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   timeout: 5000

development:
  adapter: sqlite3
  database: db/que-hacer.sqlite3

test:
  adapter: sqlite3
  database: db/que-hacer-test.sqlite3

production:
  adapter: sqlite3
  database: db/que-hacer-prod.sqlite3